# Generated by Django 4.2.7 on 2023-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='interview_status',
            field=models.CharField(choices=[('done', 'Done'), ('schedule', 'Schedule')], default='schedule', max_length=50),
        ),
    ]
